### ISSUE TITLE
ONNXscript does not work with typing_extensions < 4.10

### ISSUE THREAD

**Issue by Johansmm** [microsoft/onnxscript#1996]
When I install the following packages:

```
pip install `typing_extensions==4.9` # Force to raise the error
pip install onnxscript
```

An error is raised trying to import onnxscript:

```python
import onnxscript
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/__init__.py", line 64, in <module>
    from .backend.onnx_export import export2python as proto2python
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/backend/onnx_export.py", line 12, in <module>
    import onnxscript.onnx_types
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/onnx_types.py", line 12, in <module>
    import onnxscript.ir
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/ir/__init__.py", line 81, in <module>
    from onnxscript.ir import convenience, passes, serde, traversal
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/ir/convenience.py", line 14, in <module>
    from onnxscript.ir._convenience import (
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/ir/_convenience.py", line 23, in <module>
    from onnxscript.ir import _core, _enums, _protocols, serde, tensor_adapters
  File "/usr/local/lib/python3.11/dist-packages/onnxscript/ir/_core.py", line 41, in <module>
    from typing_extensions import TypeIs
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/usr/local/lib/python3.11/dist-packages/typing_extensions.py)
```

Note this is fixed if `typing_extensions>4.9` but this should be a requirement when installing the package.

**Comment by justinchuby** [comment]
Thanks - would you like to create a PR to add the requirement in pyproject.toml?
